packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@fission-ai/openspec": true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  protobufjs: true
  sharp: true
  ssh2: true
